/* eslint-disable */
import { Button, Stack, TextInput } from "@mantine/core";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

const Home: NextPage = () => {
  // const ambassadors = api.ambassadors.getAll.useQuery({
  //   id: "clehapr800000uta4lstqovd8",
  // });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BitLinkBuilder></BitLinkBuilder>
      <StripeLinkBuilder></StripeLinkBuilder>
      <NedarimLinkBuilder></NedarimLinkBuilder>
      {/* <Link href={"/forms/bit"}> bit</Link>
      <Link href={"/forms/stripe"}>stripe </Link>
      <Link href={"/forms/nedarim-credit"}>nedarim </Link> */}
    </>
  );
};

const BitLinkBuilder = () => {
  const [Multiplier, setMultiplier] = useState(1);
  const [id, setid] = useState("");
  const [amb, setamb] = useState("");
  const [mosadId, setmosadId] = useState("");
  const [apiValid, setapiValid] = useState("");

  //   const submit = (e: React.FormEvent<HTMLFormElement>) => {
  //     e.preventDefault();

  //     window.location.href = "/forms/bit"
  //   }
  return (
    <form className="m-6" dir="ltr">
      <Stack>
        Bit
        <TextInput
          label="id"
          value={id}
          onChange={(e) => setid(e.target.value)}
        />
        <TextInput
          label="amb"
          value={amb}
          onChange={(e) => setamb(e.target.value)}
        />
        <TextInput
          label="mosadId"
          value={mosadId}
          onChange={(e) => setmosadId(e.target.value)}
        />
        <TextInput
          label="apiValid"
          value={apiValid}
          onChange={(e) => setapiValid(e.target.value)}
        />
        <TextInput
          label="Multiplier"
          value={Multiplier}
          onChange={(e) => setMultiplier(parseInt(e.target.value))}
        />
        <Link
          href={`/forms/bit?id=${id}&amb=${amb}&mosadId=${mosadId}&apiValid=${apiValid}&Multiplier=${Multiplier}`}
        >
          <Button>Go To Bit Page </Button>
        </Link>
      </Stack>
    </form>
  );
};

const StripeLinkBuilder = () => {
  const [Multiplier, setMultiplier] = useState(1);
  const [id, setid] = useState("");
  const [amb, setamb] = useState("");

  return (
    <form className="m-6" dir="ltr">
      <Stack>
        Stripe
        <TextInput
          label="id"
          value={id}
          onChange={(e) => setid(e.target.value)}
        />
        <TextInput
          label="amb"
          value={amb}
          onChange={(e) => setamb(e.target.value)}
        />
        <TextInput
          label="Multiplier"
          value={Multiplier}
          onChange={(e) => setMultiplier(parseInt(e.target.value))}
        />
        <Link
          href={`/forms/stripe?id=${id}&amb=${amb}&Multiplier=${Multiplier}`}
        >
          <Button>Go To Stripe Page</Button>
        </Link>
      </Stack>
    </form>
  );
};

const NedarimLinkBuilder = () => {
  const [Multiplier, setMultiplier] = useState(1);
  const [id, setid] = useState("");
  const [amb, setamb] = useState("");
  const [Mosad1, setMosad1] = useState("");
  const [Mosad2, setMosad2] = useState("");

  return (
    <form className="m-6" dir="ltr">
      <Stack>
        Bit
        <TextInput
          label="id"
          value={id}
          onChange={(e) => setid(e.target.value)}
        />
        <TextInput
          label="amb"
          value={amb}
          onChange={(e) => setamb(e.target.value)}
        />
        <TextInput
          label="Mosad1"
          value={Mosad1}
          onChange={(e) => setMosad1(e.target.value)}
        />
        <TextInput
          label="Mosad2"
          value={Mosad2}
          onChange={(e) => setMosad2(e.target.value)}
        />
        <TextInput
          label="Multiplier"
          value={Multiplier}
          onChange={(e) => setMultiplier(parseInt(e.target.value))}
        />
        <Link
          href={`/forms/nedarim-credit?id=${id}&amb=${amb}&Mosad1=${Mosad1}&Mosad2=${Mosad2}&Multiplier=${Multiplier}`}
        >
          <Button>Go To Nedarim Page</Button>
        </Link>
      </Stack>
    </form>
  );
};

export default Home;

// const AuthShowcase: React.FC = () => {
//   const { data: sessionData } = useSession();

//   const { data: secretMessage } = api.example.getSecretMessage.useQuery(
//     undefined, // no input
//     { enabled: sessionData?.user !== undefined }
//   );

//   return (
//     <div className="flex flex-col items-center justify-center gap-4">
//       <p className="text-center text-2xl text-white">
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//         {secretMessage && <span> - {secretMessage}</span>}
//       </p>
//       <button
//         className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//         onClick={sessionData ? () => void signOut() : () => void signIn()}
//       >
//         {sessionData ? "Sign out" : "Sign in"}
//       </button>
//     </div>
//   );
// };
